version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-28
    environment:
    - JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Download Dependencies
        command: ./gradlew androidDependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    - run:
        name: Run Tests
        command: ./gradlew clean lint test
    - run:
        name: Code Climate Test Setup
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
    - run:
        name: Code Climate Pretest
        command: ./cc-test-reporter before-build
    - run:
        name: Generate JaCoCo report
        command: ./gradlew jacocoTestReport
    - run:
        name: Upload coverage to code climate
        command: |
          export JACOCO_SOURCE_PATH=app/src/main/java
          ./cc-test-reporter format-coverage app/build/reports/jacocoTestReport/jacocoTestReport.xml -t jacoco
          ./cc-test-reporter upload-coverage -r ${CC_TEST_REPORTER_ID}
    - store_artifacts:
        path: app/build/reports
        destination: reports
    - store_test_results:
        path: app/build/test-results
workflows:
  version: 2
  workflow:
    jobs:
    - build
